In [1]:
# Start Numpy
import numpy as np

In [2]:
data = [1,2,3,4,5] #Data List
data

[1, 2, 3, 4, 5]

In [3]:
np.array(data) # Mengubah List menjadi Numpy Array

array([1, 2, 3, 4, 5])

In [4]:
np.arange(0,10) # Membuat array dari 0 sampai 10 anggota

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2) # 2 merupakan jarak antar data atau kelipatan

array([0, 2, 4, 6, 8])

In [6]:
# Array Dummy
np.linspace(0,10,3) # Angka dalam rentang 0 dan 10 dengan 3 data

array([ 0.,  5., 10.])

In [7]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
# Array Dummy secara random
np.random.rand(3)

array([0.97799493, 0.77290445, 0.14912034])

In [9]:
np.random.rand(5,7) # 5 baris 7 kolom

array([[0.70546023, 0.49628877, 0.59751528, 0.22293164, 0.14328013,
        0.01436256, 0.57734343],
       [0.59890277, 0.06524395, 0.14434818, 0.78666715, 0.0166905 ,
        0.58177351, 0.51107425],
       [0.73164835, 0.26957382, 0.67542448, 0.51840909, 0.84812435,
        0.52459976, 0.97471149],
       [0.89514289, 0.3874    , 0.92541584, 0.90566827, 0.64689285,
        0.48379114, 0.0345972 ],
       [0.90066565, 0.55644444, 0.92702671, 0.82727115, 0.50923985,
        0.91968793, 0.60513727]])

In [10]:
# Jika ingin bilangan randomnya juga ada negatif
np.random.randn(5,5)

array([[-1.13519002, -0.18806481,  0.81846604,  0.43948433, -0.40107095],
       [-0.60532777, -0.2454768 , -0.5376155 ,  0.16832711,  0.42740194],
       [ 0.42159102,  0.66521468,  0.07110112, -0.44979768,  1.78814485],
       [ 0.14973267,  0.54834289,  0.40692567,  1.19771564,  0.30272142],
       [-0.35952897,  1.11580745,  0.06885745, -0.18257776,  0.06034271]])

In [11]:
# Jika ingin datanya integer
np.random.randint(1,50) # Data dlm rentang 1 dan 50

32

In [12]:
np.random.randint(1,50,10) # 10 adalah banyak datanya

array([10, 18, 39,  4, 33, 30,  3, 37, 15, 24])

In [13]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
# Mengubah bentuk array dari 1D menjadi 2D
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr.max() # Mencari nilai array terbesar

24

In [16]:
arr.min() # Mencari nilai array terkecil

0

In [17]:
arr.argmax() # Agregat max adalah mencari index terbesar

24

In [18]:
arr.argmin() # Agregat max adalah mencari index terkecil

0

In [19]:
arr.sum() # Menjumlahkan semua array

300